version: '3'

services:
  redis-test:
    image: redis-test:1.0
    networks:
      redis-network:
        ipv4_address: 10.5.0.2

  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
    networks:
      redis-network:
        ipv4_address: 10.5.0.4


networks:
  redis-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1